text_lang = {
    "ru": {
        "Subscribe to channel": "Подписаться на канал",
        "Check subscription": "Проверить подписку",
        "Change Language": "Смена языка",
        "Instruction": "Инструкция",
        "Support": "Поддержка",
        "Signals": "Сигналы",
        "Back": "Назад",
        "Register": "Регистрация",
        "Check registration": "Проверить регистрацию",
        "Please subscribe to the channel to continue": "Пожалуйста, подпишитесь на канал, чтобы продолжить",
        "Main menu": "Главное меню",
        "Thanks! You are subscribed ✅": "Спасибо! Вы подписаны ✅",
        "For registration, please follow the link": "Для регистрации перейдите по ссылке",
        "Register for signals:": "Регистрация для сигналов:",
        "You are registered ✅": "Вы зарегистрированы ✅",
        "You are not registered ❌": "Вы еще не зарегистрированы ❌"
    },
    "kg": {
        "Subscribe to channel": "Каналга жазылуу",
        "Check subscription": "Жазылууну текшерүү",
        "Change Language": "Тилди алмаштыруу",
        "Instruction": "Көрсөтмө",
        "Support": "Колдоо",
        "Signals": "Сигналдар",
        "Back": "Аркага",
        "Register": "Каттоо",
        "Check registration": "Каттоону текшерүү",
        "Please subscribe to the channel to continue": "Каналга жазылыңыз, андан кийин уланта аласыз",
        "Main menu": "Негизги меню",
        "Thanks! You are subscribed ✅": "Рахмат! Жазылгансың ✅",
        "For registration, please follow the link": "Каттолууга ссылага отунуз",
        "Register for signals:": "Сигналдар үчүн каттоо:",
        "You are registered ✅": "Сиз катталгансыз ✅",
        "You are not registered ❌": "Сиз каттала элексиз ❌"
    },
    "en": {
        "Subscribe to channel": "Subscribe to channel",
        "Check subscription": "Check subscription",
        "Change Language": "Change Language",
        "Instruction": "Instruction",
        "Support": "Support",
        "Signals": "Signals",
        "Back": "Back",
        "Register": "Register",
        "Check registration": "Check registration",
        "Please subscribe to the channel to continue": "Please subscribe to the channel to continue",
        "Main menu": "Main menu",
        "Thanks! You are subscribed ✅": "Thanks! You are subscribed ✅",
        "For registration, please follow the link": "For registration, please follow the link",
        "Register for signals:": "Register for signals:",
        "You are registered ✅": "You are registered ✅",
        "You are not registered ❌": "You are not registered ❌"
    }
}
